### ISSUE TITLE
请问如何使用自己的数据集测试

### ISSUE THREAD

**Issue by kekiii** [wzx0826/LBNet#7]
我的数据集包含LR图像和对应的HR图像，应该在哪里修改测试数据集路径呢？谢谢

**Comment by wzx0826** [comment]
> 我的数据集包含LR图像和对应的HR图像，应该在哪里修改测试数据集路径呢？谢谢

**Comment by wzx0826** [comment]
> 我的数据集包含LR图像和对应的HR图像，应该在哪里修改测试数据集路径呢？谢谢

你好，你可以尝试修改option.py里的data_dir为数据集的根目录，然后具体路径可以参考data_dir/benchmark/数据集名称/HR/，data_dir/benchmark/数据集名称/LR_bicubic/X4/， 然后在data/__init__.py里添加你的测试集文件夹名称。运行测试文件时，--data_test 数据集名称。
